### PR TITLE
Make the inverted version of Logo show white text

### PR DESCRIPTION
**Pull request by carlitoshxcx**
Captura de Tela 2021-12-09 às 17 05 34

Captura de Tela 2021-12-10 às 12 44 07

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @carlitoshxcx nice trick! can you do the same for the icon section?

**Comment by carlitoshxcx** [comment]
> Hey @carlitoshxcx nice trick! can you do the same for the icon section?

Sure @yannbf, good catch! Done!

**Comment by domyen** [comment]
Thanks @carlitoshxcx – going to merge it now 🙇‍♂️

**Comment by carlitoshxcx** [comment]
> Thanks @carlitoshxcx – going to merge it now 🙇‍♂️

Thanks for accepting the PR @domyen!  
Best

**Pull request merged**
